### ISSUE TITLE
Bug: Does not use os-specific newline

### ISSUE THREAD

**Issue by Almenon** [bitfasching/node-line-transform-stream#1]
node-line-transform-stream should use the correct newline character for the OS. For example, windows uses \r\n. I would be happy to submit a PR for this along with unit tests.

**Comment by Almenon** [comment]
The fix is very simple:
```javascript
const os_1 = require("os");
// later on ...
const lines = data.split(os_1.EOL)
```

**Comment by bitfasching** [comment]
Hi @Almenon, I wouldn't consider this a bug but a feature request. This package was never meant to support platforms other than Linux, and it does exactly what's written in the documentation: buffer input until the newline character `\n`. Anyway, feel free to file a pull request. Maybe import only the EOL character from the `os` package to avoid the ugly `os_1` variable name. Remember to also update the README accordingly.

**Comment by bitfasching** [comment]
Hi @Almenon, there is now the option to set a custom newline character other than the default `\n`.
